### ISSUE TITLE
Image not displayed on the published website

### ISSUE THREAD

**Issue by subhap15** [w201rdada/portfolio-subhap15#7]
Hi Brooks, Image is not getting displayed on the published website https://w201rdada.github.io/portfolio-subhap15/Bloom.html

However, when I right click and say "Open image in a new tab", the image opens. 

It also appears fine in the master branch. Could you please help?

**Comment by brooksambrose** [comment]
Try removing the leading backslash here: https://github.com/w201rdada/portfolio-subhap15/blame/master/02.Rmd#L19

So instead of
```
/img/Treatment-options.PNG
```
It should read 
```
img/Treatment-options.PNG
```
The first version says go to the top directory on this system and look for a folder called img. The second version says look in the current directory and look for a folder called image.

**Comment by subhap15** [comment]
Thanks!
